### ISSUE TITLE
App feezing

### ISSUE THREAD

**Issue by balintmaci** [ms-iot/virtual-shields-arduino#33] opened 2016-05-24 18:10 UTC
Hi!
I tried it with an arduino nano, duemilanova, mega
hc 05, hc 06 bluetooth chips
latest library (1.2)
latest app
the same thing happens. as soon as the app connects it freezes. I tried multiple baud rates including 9600. 
also I tried it on my pc as well as my lumia 950
Do you know what might cause this issue?
Thanks

**Comment by omikcity** [comment] 2016-06-01 06:49
Hi,
I am using Arduino Mega board and HC-05 Bluetooth module.
I want to use virtual shield but the problem is as I connect my lumia 930 with HC-05 bluetooth module which is connected to arduino mega, my app freezes and crash after some time.
I am not able to use virtual shields, I googled a lot about this issue but did not find any solution.
Kindly help me.

**Comment by JimGaleForce** [comment] 2016-06-07 00:51
what version of Windows 10 are you running on your phone(s)?

**Comment by balintmaci** [comment] 2016-06-07 16:49
Right now both my pc and phone is on slow ring so that's 14342 for pc and 14295 for phone, but had tried this app months ago and I had the same issue.
What's weird is I have no problem communicating with the arduino using the Bluetooth Serial Terminal app, so something must be wrong with the app. Any idea why it freezes?

**Comment by LycheeYum** [comment] 2016-08-31 03:35
I'm am experiencing this as well.  Both PC and phone and connect through terminal apps.  However, the app freezes when a bluetooth connection is made.  I've tried all the baud settings and still no joy.

Windows 10 AU PC
950XL Windows 10 mobile AU 
HC-06 1.8
Virtualshield 1.2.0
JSon 5.6.6


Thank you

**Comment by omikcity** [comment] 2016-08-31 05:02
I have figured out it. The solution is, download the source code of this app and deploy it to your phone/pc through visual studio 2015 instead of downloading through store.This solved my issue. 

Date: Tue, 30 Aug 2016 20:35:54 -0700

**Comment by balintmaci** [comment] 2016-08-31 12:46
That is amazing

**Comment by LycheeYum** [comment] 2016-09-01 00:59
Thank you for the reply.  I can confirm that deploying the solution via Visual Studio works on both Windows 10 and Windows 10 Mobile.

**Comment by ooeygui** [comment] 2016-12-07 03:36
Looks like the app needs an update.

**Comment by IoTGirl** [comment] 2017-06-19 23:54
Seems to be solved - closing this issue.

**Closed by IoTGirl** 2017-06-19 23:54 UTC

**Comment by Frostsovereign** [comment] 2017-11-22 13:51
Hello , can i plz have the appx to deploy to my windows phone , i am having the same issue , thnx.

**Comment by omikcity** [comment] 2017-11-22 14:10
Hi Frostsovereign,

I’ll send you the appx files once I’ve found It on my system.

Thaks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Frostsovereign** [comment] 2017-11-22 14:30
thank you i am waiting :)


________________________________
De : Omprakash Choudhary <notifications@github.com>
Envoyé : 22 novembre 2017 14:10
À : ms-iot/virtual-shields-arduino
Cc : Frostsovereign; Comment
Objet : Re: [ms-iot/virtual-shields-arduino] App feezing (#33)

Hi Frostsovereign,

I’ll send you the appx files once I’ve found It on my system.

Thaks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Frostsovereign** [comment] 2017-11-22 17:03
Hello , I am still waiting for the file, any good news, have you found it yet?

Sent from my Windows 10 phone

**Comment by Frostsovereign** [comment] 2017-11-24 18:11
Can anyone please help me , i need the appx to deploy

**Comment by Frostsovereign** [comment] 2017-11-26 01:37
hello, any good news ? i have been waiting for many days :(


________________________________
De : Omprakash Choudhary <notifications@github.com>
Envoyé : 22 novembre 2017 14:10
À : ms-iot/virtual-shields-arduino
Cc : Frostsovereign; Comment
Objet : Re: [ms-iot/virtual-shields-arduino] App feezing (#33)

Hi Frostsovereign,

I’ll send you the appx files once I’ve found It on my system.

Thaks.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
